version : '3'
services:
  web:
    build: 
      context: . #where all files and folders should be pulled from
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules #when accessing app/node_modules,access inside docker,dont map to external folder
      - .:/app #when accessing app folder ,you basically access current dir